services:
  - type: web
    name: lockzone-ai-floorplan
    runtime: python
    plan: free
    region: oregon
    buildCommand: "./build.sh"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 180 --max-requests 1000 --max-requests-jitter 50 --log-level info"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: WEB_CONCURRENCY
        value: 2
